### ISSUE TITLE
[1.8.9] Weird Failed to launch using launcherwrapper

### ISSUE THREAD

**Issue by HowardZHY** [Legacy-Fabric/fabric#137]
[latest.log](https://github.com/Legacy-Fabric/fabric/files/9079536/latest.log)
[1.8.9.json.txt](https://github.com/Legacy-Fabric/fabric/files/9079537/1.8.9.json.txt)
Is there anything wrong with my version.json ?

**Comment by arthurbambou** [comment]
It’s an issue with fabric loader, not LegacyFabric api.

**Comment by HowardZHY** [comment]
> It’s an issue with fabric loader, not LegacyFabric api.

So I should try with an older loader ?
