### ISSUE TITLE
[Suggestion] Modrinth version

### ISSUE THREAD

**Issue by Lovecrafts-Cat** [Legacy-Fabric/fabric#138]
I'd like for this mod to be uploaded to Modrinth as well, to give users that as an optional alternative to Curseforge.
_(If this was not the place to ask for this, I'm terribly sorry)_

**Comment by arthurbambou** [comment]
Don't worry it's planned, the next update will probably have a modrinth page too.

**Comment by ANDREI12333** [comment]
@Lovecrafts-Cat I'd like to correct you. This is not a mod. It is a fork of Fabric.

**Comment by arthurbambou** [comment]
LegacyFabric API latest is also available on modrinth
