### ISSUE TITLE
Stop being Microsoft please

### ISSUE THREAD

**Issue by DeexCoding** [Legacy-Fabric/fabric#141]
Please stop crashing when you can't load a mod from the mods folder, either pop up a warning message with all the mods you could not load and just run the game without them or at least make a feature that you can make an e.g. 1.8.9 folder in the mods folder and the loader will only load mods from that folder.
There's no reason to crash unless it's absolutely necessary.

**Comment by arthurbambou** [comment]
Not related to LegacyFabric, look for FabricMC/fabricloader
