### ISSUE TITLE
Couldn't locate the game!

### ISSUE THREAD

**Issue by Squidtito** [Legacy-Fabric/fabric#146]
Hi I am using Arch Linux/EndeavourOS. The launcher I am using is ATLauncher and I am using version mc 1.8.9 and API version 1.9.0. I do not have any mods installed, only the API.

![image](https://user-images.githubusercontent.com/62845931/221019688-3a78cc41-9434-48fa-bb3e-08775eb43827.png)
[fabricloader.log](https://github.com/Legacy-Fabric/fabric/files/10818024/fabricloader.log)

**Comment by arthurbambou** [comment]
The error has nothing to do with LegacyFabric. It's either a FabricLoader issue or an ATLauncher issue.

**Comment by Squidtito** [comment]
Okay, thanks for responding.
