### ISSUE TITLE
hi do you guys want a free biome api

### ISSUE THREAD

**Issue by valoeghese** [Legacy-Fabric/fabric#31]
I will make one if I get 6 thumbs up reactions within the next 24 hours

**Comment by BoogieMonster1O1** [comment]
finally
yes please do it :) 

should have these :-
* adding biomes
* syncing biome ids (look at the content registries module)
* adding features to them

**Comment by valoeghese** [comment]
\> Syncing Biome IDs
oh no

**Comment by valoeghese** [comment]
\> adding features to them
that's not how it works in these versions. Instead you manipulate the biome decorator properties  (or whatever you named it, I only know the old mcp name). For more control you override the biome's decorate/populate method.
Certain things like tree type is done in a method in the biome.

**Comment by valoeghese** [comment]
If you want to add custom features to existing biomes, instead there should be various events for world population stages. I can add that in my PR.

**Comment by valoeghese** [comment]
I know this because I started mc modding by learning biome stuff on 1.12.2, and I know that 1.8.9 world gen is very similar to 1.12.2

**Comment by BoogieMonster1O1** [comment]
> adding features to them
> that's not how it works in these versions. Instead you manipulate the biome decorator properties (or whatever you named it, I only know the old mcp name). For more control you override the biome's decorate/populate method.
> Certain things like tree type is done in a method in the biome.

check out #30 
that was for ores
shedaniel didn't like it though so I closed it

**Comment by valoeghese** [comment]
Back in 1.12.2 forge days we just hooked into the world decoration event and checked if the biome matched our conditions

**Comment by BoogieMonster1O1** [comment]
> If you want to add custom features to existing biomes, instead there should be an event for biome decoration/population. I can add that in my PR.

finally someone other than me is making an enhancement pull request

**Comment by BoogieMonster1O1** [comment]
> Back in 1.12.2 forge days we just hooked into the world decoration event and checked if the biome matched our conditions

that would be suitable for us too

**Comment by BoogieMonster1O1** [comment]
might probably need multiple callbacks

**Comment by valoeghese** [comment]
Forge literally had an event for every single feature in addition to it's world gen decoration callback. I'm *not* implementing that. :wink:

**Comment by valoeghese** [comment]
Just a single callback

**Comment by BoogieMonster1O1** [comment]
which is?

**Comment by valoeghese** [comment]
I mean, I'll implement the useful callbacks, just won't have an event posted for every single vanilla feature like forge does lol

**Comment by BoogieMonster1O1** [comment]
so what are these *useful callbacks*?
could you give some examples of what you plan to implement?

**Comment by valoeghese** [comment]
**not** this https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/patches/minecraft/net/minecraft/world/biome/BiomeDecorator.java.patch

**Comment by BoogieMonster1O1** [comment]
I had done something similar in #30 
but, shedaniel didn't like it so 🦀

**Comment by valoeghese** [comment]
Most Likely:
- hills/shores/rivers if I have time. don't want to overdo it
- definitely vanilla continental biome gen and fabric's variant system (the latter of which I think I wrote half of anyway)
- world decoration callback

**Comment by valoeghese** [comment]
Idk how ID sync works so if you want that someone would have to tell me

**Comment by BoogieMonster1O1** [comment]
ids are written and read from a file

**Comment by valoeghese** [comment]
well, I know how to do it as in per-world registries, as I wrote that for cursed legacy. But not networking

**Comment by BoogieMonster1O1** [comment]
registering of biomes may have to happen in content-registries-v1

**Comment by BoogieMonster1O1** [comment]
syncing raw ids is done by writing them to a file. so removing a mod doesn't break your worlds

**Comment by valoeghese** [comment]
I thought you were talking about server-client sync

**Comment by valoeghese** [comment]
I know how to sync raw ids per world as I wrote cursed legacy's version of that.
I just can't do server-client sync

**Comment by BoogieMonster1O1** [comment]
we've never had any issues about syncing ids across sides *yet*

**Comment by BoogieMonster1O1** [comment]
@shedaniel what do you think about per world biome ids?

**Comment by valoeghese** [comment]
Making id sync in beta 1.7.3 tiles was a pain btw :wink:

**Comment by BoogieMonster1O1** [comment]
oh yea I think ids in content registries are done per world

**Comment by valoeghese** [comment]
anyway I only have 1/6 thumbs up reactions so far, so I might not even make the pr :tiny_Potao

**Comment by valoeghese** [comment]
noooo not the :bike: :house:

**Comment by BoogieMonster1O1** [comment]
6 thumbs ups and i'll remove it because something's actually gonna happen then 😜

**Comment by BoogieMonster1O1** [comment]
you got three 👍 already :tiny_potato:

**Comment by BoogieMonster1O1** [comment]
now four ;)

**Comment by BoogieMonster1O1** [comment]
now five :D

**Comment by BoogieMonster1O1** [comment]
six!!!!!!

**Comment by smonnnn** [comment]
now six :)

**Comment by BoogieMonster1O1** [comment]
![image](https://user-images.githubusercontent.com/62552372/90394063-94e29f80-e0af-11ea-833c-277d3d6a8f54.png)
that was quick

**Comment by TheMadHau5** [comment]
![image](https://user-images.githubusercontent.com/35187665/90397943-3a990d00-e0b6-11ea-8ef9-84b84ed7748f.png)
commentceptioned 1 hour ago

**Comment by valoeghese** [comment]
NOO you can't just make me spend 1 hour writing the biome api!!!1!!1!1!

**Comment by valoeghese** [comment]
Haha I have school first and then my D&D group so you'll have to wait :smirk:

**Comment by valoeghese** [comment]
![image](https://user-images.githubusercontent.com/46117728/90451868-ec7d1b80-e140-11ea-9b0b-4e2395098feb.png)
How tf r u guys so popular

**Comment by valoeghese** [comment]
look at this. yall're a suggested search. Not "past search." **Suggested**

**Comment by valoeghese** [comment]
Also how do I know this isn't just you and your 8 alts :Wink:

**Comment by valoeghese** [comment]
shedaniel is now officially a boogiemonster101 alt

**Comment by valoeghese** [comment]
How in the actual f*k have you not mapped the OverworldChunkGenerator yet. It's literally `class_427`

**Comment by valoeghese** [comment]
at least I'm familiar enough with the code to be able to deal with it when it's obf

**Comment by valoeghese** [comment]
method_1323 is the decoration/population of features

**Comment by valoeghese** [comment]
field_901 controls whether sand should fall instnatly and stuff

**Comment by valoeghese** [comment]
HOW THE ACTUAL F*CK DID YOU MAP THE BIOME DECORATION METHOD AS BUILD SURFACE WTF

**Comment by hYdos** [comment]
not all of us know biomes well

**Comment by valoeghese** [comment]
idot :irr

**Comment by hYdos** [comment]
irr

**Comment by hYdos** [comment]
fake news. no biome api. fix or remove. no mcp names. format or bad

**Comment by valoeghese** [comment]
I'm also going to make an ExtendedBiome interface which can be used for biomes to edit some aspects of world gen not controlled by the biome decorator (lakes)

**Comment by BoogieMonster1O1** [comment]
@valoeghese I told people on every discord server I was in where I wouldn't get banned to go put a thumbs up on the comment 😉

**Comment by hYdos** [comment]
valoghese closed their pr.
