### ISSUE TITLE
parse .json language files on 1.8.9

### ISSUE THREAD

**Issue by creeper123123321** [Legacy-Fabric/fabric#89]

**Comment by BoogieMonster1O1** [comment]
this is probably out of scope of fabric api

**Comment by halotroop2288** [comment]
It is out of scope, but can still be done in pretty much any project, using a shadow of https://github.com/falkreon/Jankson

You need to add `id 'com.github.johnrengelman.shadow' version '7.0.0'` to your `plugins {}` block, then `shadow("blue.endless:jankson:1.2.1")` to your `dependencies {}` block.

This library supports features of JSON, HJSON, and JSON5.

**Comment by hYdos** [comment]
closing as it seems to of been resolved.
